### ISSUE TITLE
Tesstesss

### ISSUE THREAD

**Issue by JoaoPedro110** [Mayck-E/aprendendoCSS#1]
Ou pq vc utiliza muito as divs

**Comment by Mayck-E** [comment]
esqueci a tag para por semântica, vou trocar por <article>

**Comment by JoaoPedro110** [comment]
> esqueci a tag para por semântica, vou trocar por article

Blz , ou vc utiliza alguma outra extensão no vs code?

**Comment by Mayck-E** [comment]
não
só essas q o prof usa

**Comment by JoaoPedro110** [comment]
> não só essas q o prof usa

ata

**Comment by Mayck-E** [comment]
![image](https://user-images.githubusercontent.com/124847684/225386869-13476845-4941-41e7-8468-e87a7f562e81.png)
seleciona uma pasta superior

**Comment by Mayck-E** [comment]
ou arrasta umm arquivo especifico para o vs code

**Comment by JoaoPedro110** [comment]
mas eu fiz isso mas o do css esta sumindo , tem que fazer com a pasta do git hub ou so a pasta do arquivo que queremos?

**Comment by JoaoPedro110** [comment]
descobri , valeu
